// Build-time IP discovery for the mobile APK.
//
// We're building a Capacitor APK on the machine that runs the backend.
// On first launch the mobile app shows <ServerSetup /> asking for the
// backend URL — but the desktop already KNOWS its own reachable IPs at
// build time, so we bake a ranked list into the bundle and pre-fill
// the input. The user just taps Connect (or picks an alternate chip).
//
// Ranking, highest priority first:
//   1. Tailscale HTTPS DNS name (`https://*.ts.net`) when the local
//      Tailscale daemon reports one.
//   2. Tailscale (CGN range 100.64.0.0/10) — typically reachable from
//      anywhere on the user's tailnet.
//   3. RFC1918 LAN (10/8, 172.16/12, 192.168/16).
//   4. Anything else non-loopback (last resort).
//
// Port defaults to Better Agent's backend default. Override via BA_BACKEND_PORT.
//
// Writes a TS module the SPA imports. Idempotent — safe to run on every
// build. Tolerates failure: if discovery throws, the SPA falls back to
// an empty list and the user types the IP manually.

import { networkInterfaces } from "node:os";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";

const DEFAULT_BACKEND_PORT = "18765";
const PORT = process.env.BA_BACKEND_PORT || DEFAULT_BACKEND_PORT;

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "../src/serverCandidates.generated.ts");

function ipv4ToInt(ip) {
  return ip
    .split(".")
    .reduce((acc, oct) => (acc << 8) + Number(oct), 0) >>> 0;
}

const TAILSCALE_START = ipv4ToInt("100.64.0.0");
const TAILSCALE_END = ipv4ToInt("100.127.255.255");
const RANGES_LAN = [
  ["10.0.0.0", "10.255.255.255"],
  ["172.16.0.0", "172.31.255.255"],
  ["192.168.0.0", "192.168.255.255"],
].map(([a, b]) => [ipv4ToInt(a), ipv4ToInt(b)]);

function classify(ip) {
  const n = ipv4ToInt(ip);
  if (n >= TAILSCALE_START && n <= TAILSCALE_END) return 0; // tailscale
  for (const [a, b] of RANGES_LAN) if (n >= a && n <= b) return 1; // lan
  return 2; // other
}

export function tailscaleHttpsCandidateFromStatus(status) {
  if (!status || typeof status !== "object") return "";
  if (typeof status.BackendState === "string" && status.BackendState.toLowerCase() !== "running") return "";
  const self = status.Self;
  if (!self || typeof self !== "object") return "";
  if (self.Online === false) return "";
  if (typeof self.DNSName !== "string") return "";
  const host = self.DNSName.trim().toLowerCase().replace(/\.+$/, "");
  if (!/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?\.ts\.net$/.test(host)) return "";
  return `https://${host}`;
}

function currentTailscaleHttpsCandidate() {
  try {
    const stdout = execFileSync("tailscale", ["status", "--json"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 1500,
    });
    return tailscaleHttpsCandidateFromStatus(JSON.parse(stdout));
  } catch {
    return "";
  }
}

export function collectCandidates({ ifaces = networkInterfaces(), tailscaleHttps = currentTailscaleHttpsCandidate() } = {}) {
  const out = [];
  if (tailscaleHttps) out.push({ url: tailscaleHttps, iface: "", rank: -1 });
  for (const name of Object.keys(ifaces)) {
    for (const e of ifaces[name] || []) {
      if (e.family !== "IPv4" || e.internal) continue;
      out.push({ url: `http://${e.address}:${PORT}`, iface: name, rank: classify(e.address) });
    }
  }
  // Stable sort: rank ascending, then interface name for determinism.
  out.sort((a, b) => a.rank - b.rank || a.iface.localeCompare(b.iface));
  return [...new Set(out.map((e) => e.url))];
}

export function writeCandidates(candidates) {
  const body = `// AUTO-GENERATED by scripts/detect-ips.mjs — do not edit.
// Re-runs on every \`npm run build:mobile\`.
export const SERVER_CANDIDATES: readonly string[] = ${JSON.stringify(
  candidates,
  null,
  2,
)};
`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
}

export function main() {
  let candidates = [];
  try {
    candidates = collectCandidates();
  } catch (e) {
    console.error("[detect-ips] discovery failed, writing empty list:", e);
  }

  writeCandidates(candidates);
  console.log(
    `[detect-ips] wrote ${candidates.length} candidate(s) → ${outPath}`,
  );
  for (const c of candidates) console.log(`  - ${c}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
