#!/bin/bash
# install-bagent.sh — install the `bagent` CLI command onto PATH.
#
# Generates a thin launcher at $BAGENT_BIN_DIR/bagent (default ~/.local/bin)
# that execs the backend venv python on cli.py. cli.py's own directory is
# auto-added to sys.path[0], so its top-level imports resolve from any cwd.
# Idempotent — safe to re-run on every install/update.
set -e

DIR="$(cd "$(dirname "$0")/.." && pwd)"   # repo root (scripts/ lives under it)
BACKEND="$DIR/backend"
PY="${BETTER_AGENT_BACKEND_PYTHON:-}"
if [ -z "$PY" ]; then
  ACTIVE_ENV="$(python3 "$BACKEND/dependency_plan.py" active)"
  PY="$ACTIVE_ENV/bin/python"
fi
CLI="$BACKEND/cli.py"

if [ ! -x "$PY" ]; then
  echo "bagent: backend venv python not found at $PY" >&2
  exit 1
fi
if [ ! -f "$CLI" ]; then
  echo "bagent: cli not found at $CLI" >&2
  exit 1
fi

BIN_DIR="${BAGENT_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"
TARGET="$BIN_DIR/bagent"

cat > "$TARGET" <<EOF
#!/bin/bash
# Better Agent CLI launcher — generated by install-bagent.sh. Do not edit.
exec "$PY" "$CLI" "\$@"
EOF
chmod +x "$TARGET"
echo "bagent installed → $TARGET"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "NOTE: $BIN_DIR is not on your PATH. Add this to your shell profile:" >&2
     echo "      export PATH=\"$BIN_DIR:\$PATH\"" >&2 ;;
esac
